/* CS317 Distributed Systems – Cairo University quiz data */
const QUIZ_DATA = {
  chapters: [
    {
      id: 1,
      title: "Chapter 1 – Introduction to Distributed Systems",
      mcq: [
        { q: "What is a distributed system?", opts: ["A single mainframe computer", "A collection of independent computers that appears to users as a single coherent system", "A cluster of identical processors sharing a single OS", "A network of printers and storage devices"], a: 1 },
        { q: "Which of the following is a characteristic of a distributed system?", opts: ["Users must know where each resource resides", "It is easy to expand or scale", "Resources are always centralized", "All software runs on a single machine"], a: 1 },
        { q: "Which term explains hiding the fact that resources are distributed across a network?", opts: ["Location transparency", "Migration transparency", "Transparency", "Concurrency transparency"], a: 2 },
        { q: "Which of the following is NOT listed as a motivation for using distributed systems?", opts: ["Resource sharing", "Availability", "Extensibility", "Monolithic design"], a: 3 },
        { q: "In the context of distributed systems, what does \"Digital Firm\" refer to?", opts: ["A traditional paper-based business", "A firm with no digital processes", "A firm with digitally enabled relationships and rapid sensing/response to changes", "A company entirely run on legacy systems"], a: 2 },
        { q: "The middleware in a distributed system is positioned between which layers?", opts: ["User programs and hardware", "Higher-level applications and the local OS", "The operating system and the hardware", "The network layer and the database"], a: 1 },
        { q: "Which example illustrates a distributed system where users are unaware of how orders flow?", opts: ["A personal laptop", "A workflow information system used across departments", "A standalone spreadsheet", "A single file server"], a: 1 },
        { q: "Which example is used to describe the World Wide Web as a distributed system?", opts: ["Centralized file system", "A uniform model where documents appear regardless of server", "A single database server", "A local directory service only"], a: 1 },
        { q: "What is one of the four important goals for building a distributed system?", opts: ["Complexity", "Opacity", "Transparency", "Inflexibility"], a: 2 },
        { q: "What is meant by \"access transparency\"?", opts: ["Hiding where data is physically stored", "Hiding the differences in data representation and access methods", "Hiding the time at which a resource responds", "Hiding who is requesting the resource"], a: 1 },
        { q: "Which type of transparency hides that a resource may move to another location?", opts: ["Location transparency", "Migration transparency", "Relocation transparency", "Replication transparency"], a: 1 },
        { q: "Which type of transparency deals with hiding that a resource is replicated?", opts: ["Replication transparency", "Concurrency transparency", "Failure transparency", "Access transparency"], a: 0 },
        { q: "What is \"concurrency transparency\" concerned with?", opts: ["Hiding that multiple copies exist", "Hiding the fact that a resource is shared by several users", "Hiding the network latency", "Hiding the existence of a global clock"], a: 1 },
        { q: "Which transparency type masks whether a resource is in memory or on disk?", opts: ["Persistence transparency", "Access transparency", "Location transparency", "Migration transparency"], a: 0 },
        { q: "What does an \"open\" distributed system emphasize?", opts: ["Proprietary protocols", "Standard rules describing service syntax and semantics", "Exclusive use of one vendor's technology", "Hidden interfaces"], a: 1 },
        { q: "In the context of openness, what does \"interoperability\" mean?", opts: ["The ability to intermix components from different manufacturers", "The requirement to replace all components when upgrading", "The use of a single programming language", "The need for identical hardware across all nodes"], a: 0 },
        { q: "Which term describes an application's ability to execute on different distributed systems without modification?", opts: ["Interoperability", "Portability", "Flexibility", "Scalability"], a: 1 },
        { q: "Which dimension is NOT listed among the three primary scalability dimensions?", opts: ["Size", "Geographical", "Temporal", "Administrative"], a: 2 },
        { q: "What is a key characteristic of decentralized algorithms?", opts: ["Every machine has complete information about the system state", "Machines make decisions based on local information", "The global clock is required", "Algorithms rely on a central authority"], a: 1 },
        { q: "In synchronous vs. asynchronous communication, which statement is correct?", opts: ["Synchronous is always faster than asynchronous", "Synchronous communication happens in real time; asynchronous does not require all parties online at the same time", "Asynchronous communication requires real-time interaction", "Synchronous communication cannot be used over wide-area networks"], a: 1 },
        { q: "What is described as a drawback of replication and caching?", opts: ["They always improve consistency", "They can lead to data consistency problems", "They eliminate latency entirely", "They require no coordination"], a: 1 },
        { q: "What is the primary purpose of using DNS-like distribution techniques in scalability?", opts: ["To centralize authority", "To divide a namespace into zones and route requests efficiently", "To store all data in a single location", "To prevent replication"], a: 1 },
        { q: "Which technique is described as reducing the overall communication?", opts: ["Hiding communication latencies", "Replication", "Asynchronous communication", "Moving computation to the client"], a: 0 },
        { q: "What does \"asynchronous communication\" enable in interactive applications?", opts: ["Waiting for a server reply before doing anything else", "Doing other useful work while waiting for a reply", "Blocking the client until the server responds", "Ensuring all responses arrive in order"], a: 1 },
        { q: "Which example illustrates distributing a single DNS-like service across zones?", opts: ["A single local DNS server servicing all domains", "A hierarchical DNS with zone-specific servers", "A single central database for all domain data", "A peer-to-peer DNS with no servers"], a: 1 },
        { q: "Ease of configuring the system from different components from different developers is known as:", opts: ["Interoperability", "Portability", "Flexibility", "Openness"], a: 2 },
        { q: "A system supporting replication transparency should also support:", opts: ["Access transparency", "Failure transparency", "Location transparency", "Concurrency transparency", "Access and location transparency (1 and 3)", "All of the previous"], a: 4 },
        { q: "A system supporting migration transparency should also support:", opts: ["Access transparency", "Failure transparency", "Location transparency", "Concurrency transparency", "Access and location transparency (1 and 3)", "All of the previous"], a: 4 },
        { q: "A system supporting failure transparency should also support:", opts: ["Access transparency", "Replication transparency", "Location transparency", "Concurrency transparency", "All of the previous", "None of the previous"], a: 1 },
        { q: "A system supporting concurrency transparency should also support:", opts: ["Access transparency", "Replication transparency", "Location transparency", "Failure transparency", "All of the previous", "None of the previous"], a: 5 },
        { q: "Microsoft Word reading Excel files is an example of:", opts: ["Portable system", "Interoperable system", "Access transparent system", "Flexible system", "All of the previous", "None of the previous"], a: 1 },
        { q: "Unix OS widely used on servers and mobile devices is an example of:", opts: ["Portable system", "Interoperable system", "Access transparent system", "Flexible system", "All of the previous", "None of the previous"], a: 0 },
        { q: "Windows 8: easy to add/replace modules without affecting others is an example of:", opts: ["Portable system", "Interoperable system", "Access transparent system", "Flexible system", "All of the previous", "None of the previous"], a: 3 },
        { q: "Which is a distributed system characteristic?", opts: ["Differences between computers hidden from users", "Easy to expand or scale", "Continuously available", "Users interact regardless of where/when", "2 and 3 only", "All of the previous"], a: 5 },
        { q: "Hiding that processes/resources are physically distributed across multiple computers means:", opts: ["Openness", "Scalability", "Availability", "Transparency", "1 and 2", "All of the previous"], a: 3 },
        { q: "NFS: same commands for local or remote files means:", opts: ["Access transparency", "Openness", "Location transparency", "Concurrency transparency", "Availability", "All of the previous"], a: 0 },
        { q: "NFS: same library calls for local and remote files means:", opts: ["Access transparency", "Openness", "Location transparency", "Concurrency transparency", "Availability", "All of the previous"], a: 0 },
        { q: "Video-on-demand users not knowing server IP means:", opts: ["Access transparency", "Openness", "Location transparency", "Concurrency transparency", "Availability", "All of the previous"], a: 2 },
        { q: "Programmers not knowing physical location of video server means:", opts: ["Access transparency", "Openness", "Location transparency", "Concurrency transparency", "Availability", "All of the previous"], a: 2 },
        { q: "Distributed printing with atomic access per file (no random interleaving) means:", opts: ["Access transparency", "Openness", "Location transparency", "Concurrency transparency", "Availability", "All of the previous"], a: 3 },
        { q: "User unaware video comes from replica server means:", opts: ["Access transparency", "Replication transparency", "Location transparency", "Concurrency transparency", "Availability", "All of the previous"], a: 1 },
        { q: "Moving resources while accessed without user noticing is:", opts: ["Migration transparency", "Location transparency", "Relocation transparency", "All of the previous"], a: 0 },
        { q: "The goal of middleware is:", opts: ["Virtual shared memory on multicomputer", "Virtual tightly-coupled machine on multicomputer", "Virtual shared memory on loosely-coupled system", "All of the previous", "None of the previous"], a: 3 },
        { q: "Ease of configuring from different developers' components is:", opts: ["Interoperability", "Portability", "Flexibility", "All of the previous"], a: 2 },
        { q: "A system offering services according to standard rules is:", opts: ["Transparent system", "Open system", "Scalable system", "All of the previous"], a: 1 },
        { q: "Moving resources without affecting how they are accessed is:", opts: ["Migration transparency", "Location transparency", "Relocation transparency", "All of the previous"], a: 2 },
        { q: "Replication:", opts: ["Increases availability", "Balances load between components", "Hides communication latency problems", "All of the previous", "None of the previous"], a: 3 }
      ],
      tf: [
        { q: "A distributed system is a collection of independent computers appearing as one coherent system.", a: true },
        { q: "In a distributed system, it is easy to scale the system.", a: true },
        { q: "A primary motivation for distributed systems is resource sharing.", a: true },
        { q: "A \"Digital Firm\" has digitally enabled relationships and rapid sensing/response.", a: true },
        { q: "Middleware sits between higher-level applications and the local OS.", a: true },
        { q: "A workflow system across departments is an example where users are unaware of order flow.", a: true },
        { q: "The Web appears to be served from a single server only.", a: false, fix: "The Web appears to be served from multiple servers; users see a unified interface." },
        { q: "One goal for building a distributed system is transparency.", a: true },
        { q: "Access transparency hides differences in data representation and access methods.", a: true },
        { q: "Migration transparency hides that a resource may move.", a: true },
        { q: "Replication transparency hides that a resource is replicated.", a: true },
        { q: "Concurrency transparency hides that a resource is shared by several users.", a: true },
        { q: "Persistence transparency hides whether a resource is in memory or on disk.", a: true },
        { q: "Open distributed systems emphasize proprietary protocols.", a: false, fix: "Open distributed systems emphasize standard, interoperable protocols (not proprietary)." },
        { q: "Interoperability means intermixing components from different manufacturers.", a: true },
        { q: "Portability is executing on different systems without modification.", a: true },
        { q: "Scalability dimensions include size, geographical, and temporal.", a: false, fix: "The dimensions include size, geographical, and administrative (not temporal)." },
        { q: "Decentralized algorithms rely on global information about system state.", a: false, fix: "Relies on local information about the system state." },
        { q: "Synchronous communication requires all parties online at the same time.", a: true },
        { q: "Replication and caching can lead to data consistency problems.", a: true },
        { q: "DNS-like techniques route requests by dividing namespace into zones.", a: true },
        { q: "Reducing communication is achieved only by minimizing inter-node messaging.", a: false, fix: "Reducing overall communication can be achieved by strategies like caching, replication, and locality-aware processing." },
        { q: "Asynchronous communication allows useful work while waiting for a reply.", a: true },
        { q: "Hierarchical DNS with zone-specific servers illustrates DNS distribution.", a: true },
        { q: "Replication transparency does not require location transparency.", a: false, fix: "False it is necessary" },
        { q: "Asynchronous is real-time; synchronous is time-delayed.", a: false, fix: "False the contrary" },
        { q: "As security and sharing increase, security becomes more important.", a: true },
        { q: "Location transparency hides differences in data representation and access.", a: false, fix: "False access transparency" },
        { q: "To hide replication, all replicas must have the same name.", a: true },
        { q: "It is not necessary that replication transparency also requires location transparency.", a: false, fix: "False it is necessary" },
        { q: "Masking failures is one of the hardest issues in distributed systems.", a: true },
        { q: "Asynchronous communication is better than reducing overall communication for hiding latency.", a: false, fix: "False the contrary" },
        { q: "Scalability problems often appear as performance degradation.", a: true },
        { q: "Caching is decided by the client, not the resource owner.", a: true },
        { q: "Caching and replication lead to consistency problems.", a: true },
        { q: "In decentralized algorithms, no implicit global clock is assumed.", a: true },
        { q: "LANs provide reliable communication based on routing.", a: false, fix: "False broadcasting" },
        { q: "Replication decreases availability.", a: false, fix: "False increases" },
        { q: "Caching is decided by the server (owner), not the client.", a: false, fix: "False the contrary" }
      ]
    },
    {
      id: 2,
      title: "Chapter 2 – System Architectures",
      mcq: [
        { q: "A tightly coupled OS is generally referred to as:", opts: ["NOS", "DOS", "COWs", "TCOS", "All of the previous", "None of the previous"], a: 1 },
        { q: "The drawback of NUMA machines is:", opts: ["Several switching stages between CPU and memory", "Cache incoherence", "1 and 2", "Placement of programs and data", "1 and 4", "None of the previous"], a: 2 },
        { q: "Which middleware paradigm treats all resources (including I/O) as files?", opts: ["Distributed file systems", "Remote Procedure Calls", "Object orientation", "All of the previous", "None of the previous"], a: 0 },
        { q: "Which system has the highest degree of transparency?", opts: ["Multiprocessor OSs", "Multicomputer OSs", "Network OSs", "Middleware based systems", "All of the previous", "None of the previous"], a: 3 },
        { q: "Which system has only one copy of the OS?", opts: ["Multiprocessor OSs", "Multicomputer OSs", "Network OSs", "Middleware based systems", "All of the previous", "None of the previous"], a: 0 },
        { q: "Which systems are considered open?", opts: ["Multiprocessor OSs", "Multicomputer OSs", "Network OSs", "Middleware based systems", "1 and 2", "3 and 4"], a: 5 },
        { q: "Which systems manage resources locally?", opts: ["Multiprocessor OSs", "Multicomputer OSs", "Network OSs", "Middleware based systems", "1 and 2", "3 and 4"], a: 5 },
        { q: "In which systems are resources globally managed?", opts: ["Multiprocessor OSs", "Multicomputer OSs", "Network OSs", "Middleware based systems", "1 and 2", "3 and 4"], a: 4 },
        { q: "Which systems are considered closed?", opts: ["Multiprocessor OSs", "Multicomputer OSs", "Network OSs", "Middleware based systems", "1 and 2", "3 and 4"], a: 4 },
        { q: "Hiding physical distribution of processes/resources means:", opts: ["Openness", "Scalability", "Availability", "Transparency", "1 and 2", "All of the previous"], a: 3 },
        { q: "Massively Parallel Processors (MPPs) belong to:", opts: ["Multiprocessor", "Homogeneous Multicomputer", "Heterogeneous Multicomputer", "2 and 3", "All of the previous", "None of the previous"], a: 1 },
        { q: "The goal of middleware is:", opts: ["Virtual shared memory on multicomputer", "Virtual tightly-coupled machine on multicomputer", "Virtual shared memory on loosely-coupled system", "All of the previous", "None of the previous"], a: 1 },
        { q: "The goal of Distributed Shared Memory Systems is:", opts: ["Virtual shared memory on multicomputer", "Virtual tightly-coupled machine on multicomputer", "Shared memory on loosely-coupled system", "1 and 2", "2 and 3"], a: 3 },
        { q: "A Distributed Shared Memory System:", opts: ["Large virtual address space from each node", "Is a virtual shared memory machine", "Is a multicomputer system", "Programmers use semaphores/monitors", "All of the previous", "None of the previous"], a: 4 },
        { q: "Cluster Of Workstations (COWs) belongs to:", opts: ["Homogeneous Multiprocessor", "Homogeneous Multicomputer", "Heterogeneous Multicomputer", "2 and 3", "All of the previous", "None of the previous"], a: 3 },
        { q: "Communication through message passing is used in:", opts: ["Multiprocessor systems", "Multicomputer systems", "Distributed systems", "2 and 3", "All of the previous", "None of the previous"], a: 3 },
        { q: "OS maintains single global view of resources in:", opts: ["Tightly-coupled systems", "Multiprocessor systems", "Homogeneous multicomputer systems", "All of the previous", "None of the previous"], a: 3 },
        { q: "All OS data structures in shared memory in:", opts: ["Multiprocessor systems", "Multicomputer systems", "Distributed systems", "2 and 3"], a: 0 },
        { q: "Data must be protected against concurrent access in:", opts: ["Multiprocessor systems", "Multicomputer systems", "Distributed systems", "2 and 3"], a: 0 },
        { q: "OS makes number of CPUs transparent in:", opts: ["Multiprocessor OSs", "Multicomputer OSs", "Distributed systems", "1 and 3"], a: 0 },
        { q: "… is hardware/software whose value indicates status of a common resource.", opts: ["Monitors", "Semaphores", "Kernel", "1 and 2"], a: 1 },
        { q: "… is a programming construct: module of variables and procedures.", opts: ["Monitors", "Semaphores", "Kernel", "1 and 2"], a: 0 },
        { q: "Data structures cannot be shared via physically shared memory in:", opts: ["Multiprocessor OSs", "Multicomputer OSs", "Distributed systems", "1 and 3"], a: 3 },
        { q: "Goal: virtual shared memory machine on multicomputer:", opts: ["Multiprocessor systems", "Multicomputer systems", "Distributed shared systems", "2 and 3"], a: 2 },
        { q: "Address space divided into pages in:", opts: ["Multiprocessor systems", "Multicomputer systems", "Distributed shared systems", "2 and 3"], a: 2 },
        { q: "Cost of transferring a page across network is primarily:", opts: ["Cost of setting up the transfer", "Amount of data transferred", "Type of data transferred", "2 and 3"], a: 0 },
        { q: "Data of two independent processes in same page is called:", opts: ["Monitors", "Semaphores", "Kernel", "False sharing"], a: 3 },
        { q: "In 'everything as a file' middleware, which is a file?", opts: ["Documents", "Keyboards", "Printers", "Monitors", "All of the previous"], a: 4 },
        { q: "Middleware: process calls procedure on remote machine:", opts: ["Everything is a file", "RPCs", "Distributed file systems", "Object orientation"], a: 1 },
        { q: "Middleware: invoke remote objects transparently:", opts: ["Everything is a file", "RPCs", "Distributed file systems", "Object orientation"], a: 3 },
        { q: "Which is a middleware service?", opts: ["Name service", "RPC service", "DFS service", "Object orientation service"], a: 0 },
        { q: "Which is a middleware service?", opts: ["Persistence service", "RPC service", "DFS service", "Object orientation service"], a: 0 },
        { q: "Which is a middleware service?", opts: ["Distributed transactions services", "RPC service", "DFS service", "Object orientation service"], a: 0 },
        { q: "Which is a middleware service?", opts: ["Security services", "RPC service", "DFS service", "Object orientation service"], a: 0 },
        { q: "Middleware paradigm: all resources as files:", opts: ["Distributed file systems", "RPC", "Object orientation", "None of the previous"], a: 0 }
      ],
      tf: [
        { q: "Asynchronous is real-time; synchronous is time-delayed.", a: false, fix: "False the contrary" },
        { q: "Sophisticated software is needed for heterogeneous multicomputers.", a: true },
        { q: "As connectivity increases, security becomes more important.", a: true },
        { q: "Async is better than reducing communication for hiding latency.", a: false, fix: "False the contrary" },
        { q: "Scalability problems often appear as performance degradation.", a: true },
        { q: "Caching is decided by the client, not the owner.", a: true },
        { q: "Caching and replication lead to consistency problems.", a: true },
        { q: "Multicomputers have a single shared physical address space.", a: false, fix: "False multiprocessors" },
        { q: "In multiprocessors, every CPU has its own private memory.", a: false, fix: "False the contrary" },
        { q: "Omega network problem is limited scalability.", a: false, fix: "False bus-based multiprocessors" },
        { q: "Bus-based multiprocessors have limited scalability.", a: true },
        { q: "Bus-based drawback: several switching stages CPU–memory.", a: false, fix: "False omega network" },
        { q: "Crossbar drawback: several switching stages CPU–memory.", a: false, fix: "False omega network" },
        { q: "Switch-based multicomputer messages are broadcast.", a: false, fix: "False routed" },
        { q: "Bus-based multicomputer messages are routed.", a: false, fix: "False broadcasted" },
        { q: "Distributed OS functionality matches uniprocessor OS except multiple CPUs.", a: true },
        { q: "Semaphores can lead to unstructured code.", a: true },
        { q: "Message-passing is easier than shared memory.", a: false, fix: "False the contrary" },
        { q: "Page transfer cost is mainly amount of data, not setup.", a: false, fix: "False the contrary" },
        { q: "Network OSs make serious attempt at full transparency.", a: false, fix: "False DOS" },
        { q: "Middleware manages each individual node.", a: false, fix: "False" },
        { q: "LANs use routing for reliable communication.", a: false, fix: "False broadcasting" },
        { q: "Multicomputers share one physical address space (like multiprocessors).", a: false, fix: "False multiprocessors" },
        { q: "In bus systems, messages route at each switch step.", a: false, fix: "False switch systems" },
        { q: "COWs are simple and cheap.", a: true },
        { q: "Loosely-coupled OS maintains single global resource view.", a: false, fix: "False tightly-coupled systems" },
        { q: "Multicomputer OS: only communication is message passing.", a: true },
        { q: "Skype and text chat are asynchronous.", a: false, fix: "False synchronous communication" },
        { q: "Blogs and forums are synchronous.", a: false, fix: "False asynchronous communication" },
        { q: "LANs use asynchronous communication.", a: false, fix: "False synchronous communication" },
        { q: "In two-tier architecture, server may act as client.", a: false, fix: "False three-tier" },
        { q: "In horizontal distribution, different components on different machines.", a: false, fix: "False vertical distribution" },
        { q: "Middleware sits between applications and NOS.", a: true },
        { q: "RPC: message passing is visible to programmer.", a: false, fix: "false is not visible" },
        { q: "Fault-tolerance allows operation despite component failure.", a: true },
        { q: "Cost of setting up page transfer is higher than transferring the page.", a: true },
        { q: "Switch-based multiprocessors have limited scalability.", a: false, fix: "False bus-based" },
        { q: "In connection-oriented network, packets may arrive out of order.", a: false, fix: "False connectionless" },
        { q: "With async communication, sender blocked until message stored/delivered.", a: false, fix: "False synchronous communication" },
        { q: "NOS is tightly-coupled OS for multiprocessors/homogeneous multicomputers.", a: false, fix: "False DOS" },
        { q: "In two-tier architecture, programs distributed as clients and servers.", a: true },
        { q: "In three-tier, programs distributed as pure clients and servers only.", a: false, fix: "False two-tier" },
        { q: "In two-tier, server may act as client.", a: false, fix: "False three-tier" },
        { q: "In three-tier, server may act as client.", a: true },
        { q: "Vertical distribution: different components on different machines.", a: true },
        { q: "Horizontal distribution: different components on different machines.", a: false, fix: "False vertical distribution" },
        { q: "Horizontal distribution: client/server may be replicated.", a: true },
        { q: "Vertical distribution: client/server may be replicated.", a: false, fix: "False horizontal distribution" },
        { q: "Middleware is additional layer on NOS for general-purpose services.", a: true },
        { q: "DFS middleware: no difference local vs remote file.", a: true },
        { q: "RPC: process calls remote procedure; caller unaware of network.", a: true },
        { q: "Object orientation: invoke remote objects transparently via interface.", a: true },
        { q: "OO middleware: caller unaware of network (like RPC).", a: false, fix: "False Remote Procedure Calls (RPCs)" },
        { q: "RPC: invoke remote objects transparently.", a: false, fix: "False object orientation" },
        { q: "Name services comparable to telephone books.", a: true },
        { q: "Distributed transactions operate on data across multiple machines.", a: true },
        { q: "Heterogeneous multicomputers used as parallel systems (single problem).", a: false, fix: "False Homogeneous" },
        { q: "Connection-oriented: no setup needed before first message.", a: false, fix: "False In connectionless protocols" },
        { q: "When network reliable, better to use connection-oriented protocols.", a: false, fix: "False connectionless" },
        { q: "When network unreliable, better to use connectionless protocol.", a: false, fix: "False connection-oriented" },
        { q: "In connectionless protocol, client resend on no reply is always the best solution when a message is lost.", a: false, fix: "False there is no solution to this problem" },
        { q: "Middleware sits between applications and the distributed operating system only.", a: false, fix: "False network operating system" },
        { q: "Most middleware is based on a model or paradigm for describing distribution and communication.", a: true },
        { q: "Middleware based on distributed file systems has proven reasonably scalable.", a: true },
        { q: "In object-orientation middleware, each object implements an interface hiding internal details.", a: true },
        { q: "In RPC middleware, each object implements an interface hiding internal details from users.", a: false, fix: "False object orientation" },
        { q: "In object orientation, a process calls a procedure implemented on a remote machine.", a: false, fix: "False Remote Procedure Calls (RPCs)" },
        { q: "In object orientation, object interfaces are available on many other machines.", a: true },
        { q: "The problem with switch-based multiprocessors is their limited scalability.", a: false, fix: "False bus-based" },
        { q: "In switch-based multicomputer, messages are broadcast through the network.", a: false, fix: "False routed" }
      ]
    },
    {
      id: 3,
      title: "Chapter 3 – Middleware",
      mcq: [
        { q: "Middleware is best described as:", opts: ["A hardware device", "A software layer in NOS to hide heterogeneity and improve transparency", "A database engine", "A routing protocol"], a: 1 },
        { q: "Middleware achieves which two goals together?", opts: ["Speed and encryption", "Scalability/openness of NOS and transparency/ease of DOS", "Reliability and compression only", "Power saving and hardware expansion"], a: 1 },
        { q: "Middleware sits between:", opts: ["CPU and memory", "Applications and the network operating system", "Disk and RAM", "Switch and router"], a: 1 },
        { q: "Middleware does NOT manage nodes; what does?", opts: ["The local OS", "The router", "Network cables", "Middleware always manages nodes"], a: 0 },
        { q: "Middleware hides heterogeneity mainly by:", opts: ["Removing connections", "Providing interfaces to services", "Forcing identical computers", "Disabling communication"], a: 1 },
        { q: "\"Treating everything as a file\" is called:", opts: ["Distributed databases", "Unified File Access", "Name services", "Persistence services"], a: 1 },
        { q: "UNIX/Plan 9 treats:", opts: ["Only documents as files", "Only local resources", "All resources (including I/O) as files", "Remote differently from local"], a: 2 },
        { q: "In file-as-model, local vs remote files:", opts: ["Handled differently", "Only remote can open", "No difference; same open/read/write/close", "Only local can close"], a: 2 },
        { q: "A Distributed File System (DFS) is:", opts: ["Single file on one machine", "Classical file system distributed across machines", "Firewall rules", "Naming server only"], a: 1 },
        { q: "DFS main purpose:", opts: ["Remove sharing", "Promote sharing of dispersed files", "Increase memory only", "Stop network communication"], a: 1 },
        { q: "Distribution transparency in DFS is for:", opts: ["Only processes/threads", "Only traditional data files", "Only security keys", "Only UI elements"], a: 1 },
        { q: "RPC stands for:", opts: ["Remote Process Connection", "Remote Procedure Calls", "Rapid Protocol Communication", "Register Procedure Channels"], a: 1 },
        { q: "In RPC, parameters are:", opts: ["Sent manually by programmer", "Not allowed to transfer", "Shipped transparently to remote machine", "Stored only locally"], a: 2 },
        { q: "With RPC, the calling process remains:", opts: ["Aware of network communication", "Responsible for remote execution", "Unaware of network communication", "Unable to receive results"], a: 2 },
        { q: "Object orientation in middleware enables:", opts: ["Only local invocation", "Invoking remote objects via interfaces hiding internals", "Direct access to internal state", "Disabling interfaces"], a: 1 },
        { q: "An object interface consists of:", opts: ["Only data fields", "Internal implementation", "Methods the object implements", "Only protocol name"], a: 2 },
        { q: "Naming services are concerned with:", opts: ["Encrypting data", "External names so components identified by name server", "Saving workflow in memory", "Atomic transactions"], a: 1 },
        { q: "Naming services are compared to:", opts: ["Bank ledger", "Telephone books", "Compiler", "Router table"], a: 1 },
        { q: "Key difficulty in naming:", opts: ["No lookup needed", "Scalability: lookup assumes fixed entity location", "Too many disk ops", "Lack of security keys"], a: 1 },
        { q: "Persistence services help by:", opts: ["Keeping all workflows in memory", "Removing storage need", "Unloading idle instances to save memory/scale", "Preventing databases"], a: 2 },
        { q: "Distributed transactions ensure:", opts: ["Only speed", "Atomicity across distributed data", "Compression", "Cache consistency only"], a: 1 },
        { q: "Atomicity means:", opts: ["Always partial success", "Always retries", "All writes succeed or none affect data", "Only atomic reads"], a: 2 },
        { q: "Security services in middleware must be:", opts: ["Non-invasive optional", "Invasive; cannot rely on local OS alone", "Only at routers", "Never in middleware"], a: 1 },
        { q: "Middleware may not be truly open because:", opts: ["Always more open", "Never hides heterogeneity", "Strong dependency on specific middleware", "No interfaces"], a: 2 },
        { q: "Complete interfaces mean:", opts: ["Only documentation", "Interfaces guessed by developers", "Everything needed to implement is specified", "One vendor only"], a: 2 }
      ],
      tf: [
        { q: "Middleware is a layer used in NOSs to hide heterogeneity of underlying platforms.", a: true },
        { q: "Middleware is intended to directly manage an individual network node.", a: false, fix: "The local OS manages each node." },
        { q: "Middleware improves distribution transparency in addition to hiding heterogeneity.", a: true },
        { q: "A DOS is intended to handle a collection of independent computers.", a: false, fix: "A DOS does not handle a collection of independent computers." },
        { q: "A NOS provides a view of a single coherent system.", a: false, fix: "A NOS does not provide a single coherent system view." },
        { q: "A collection of independent computers can appear to users as a single coherent system.", a: true },
        { q: "Middleware sits in the middle between applications and the network operating system.", a: true },
        { q: "Middleware is an additional layer on top of NOS implementing general-purpose services.", a: true },
        { q: "Each local system provides local resource management and simple communication means.", a: true },
        { q: "Treating everything as a file is one middleware model.", a: true },
        { q: "In the file model, all resources are files with no difference between local and remote.", a: true },
        { q: "In UNIX/Plan 9, an application reads/writes bytes by opening a file, then closes it.", a: true },
        { q: "A Distributed File System (DFS) is a single file located on one machine.", a: false, fix: "A DFS is a file system distributed across multiple machines." },
        { q: "The purpose of DFS is to promote sharing of dispersed files.", a: true },
        { q: "In DFS, distribution transparency is supported only for processes that store data.", a: false, fix: "Only for traditional files used for storing data." },
        { q: "RPC stands for Remote Procedure Calls.", a: true },
        { q: "In RPC, parameters are shipped to the remote machine, executed, then results returned.", a: true },
        { q: "With RPC, the calling process remains unaware that network communication occurred.", a: true },
        { q: "In object orientation, remote objects can be invoked transparently via interfaces.", a: true },
        { q: "In RMI, an object interface consists of the methods the object implements.", a: true },
        { q: "Naming services are about implementing security inside middleware.", a: false, fix: "Naming defines external names for components identified by a name server." },
        { q: "Name services allow entities to be shared and looked up, like telephone books.", a: true },
        { q: "Naming scalability problems arise because lookup assumes the named entity location is fixed.", a: true },
        { q: "Persistence services mainly ensure atomic transactions across distributed data.", a: false, fix: "Persistence stores long workflows so idle instances can be unloaded to save memory." },
        { q: "Complete interface definitions improve openness by specifying everything needed for implementation.", a: true }
      ]
    },
    {
      id: 4,
      title: "Chapter 4 – Client-Server Model",
      mcq: [
        { q: "In client-server model, a server is:", opts: ["Process requesting services", "Process implementing a specific service", "Network device routing packets", "Transport-layer protocol"], a: 1 },
        { q: "A client:", opts: ["Stores persistent data only", "Establishes UDP connection only", "Sends request to server and waits for reply", "Handles only network layer"], a: 2 },
        { q: "Client-server interaction is also known as:", opts: ["Push-pull behavior", "Request-reply behavior", "Publish-subscribe", "Stream control"], a: 1 },
        { q: "Connectionless communication means:", opts: ["Must establish connection first", "Message sent without prior arrangement", "Messages always guaranteed", "Always multicast"], a: 1 },
        { q: "Connectionless protocols include:", opts: ["TCP and FTP", "IP and UDP", "UDP and HTTP only", "SMTP and DNS"], a: 1 },
        { q: "Connectionless advantage:", opts: ["High overhead", "Mandatory setup", "Low overhead", "Guaranteed delivery"], a: 2 },
        { q: "Connectionless allows:", opts: ["Only unicast", "Only point-to-point", "Multicast and broadcast easily", "No retransmissions"], a: 2 },
        { q: "Connection-oriented communication is always:", opts: ["Unicast (point-to-point)", "Multicast only", "Broadcast only", "Stateless"], a: 0 },
        { q: "Connectionless protocols are usually:", opts: ["Stateful", "Stateless", "Reliable", "Encryption protocols"], a: 1 },
        { q: "Client cannot detect if original request was lost because:", opts: ["UDP confirms delivery", "Server never replies", "Connectionless protocols don't track state", "TCP always used"], a: 2 },
        { q: "If request resent after original arrived:", opts: ["No issues", "Server auto-cancels first", "Operation may be performed twice", "Reply always suppressed"], a: 2 },
        { q: "Standard approach for lost messages:", opts: ["Remove timers", "Add timeouts and retransmission at application", "Disable ACKs", "Use only connection-oriented"], a: 1 },
        { q: "With timeouts + retransmission, client:", opts: ["Waits forever", "Sends request, starts timer, resends if no reply", "Never resends", "Requires TCP handshake"], a: 1 },
        { q: "Timeouts + retransmission helps because:", opts: ["First message always arrives", "Eventually one copy reaches server", "Eliminates need for reliability", "Replies cannot be lost"], a: 1 },
        { q: "Duplicate-handling includes:", opts: ["Random page titles", "Only port numbers", "Request IDs (sequence numbers)", "Encryption keys only"], a: 2 },
        { q: "If server already processed request_id:", opts: ["Execute again", "Re-send previous reply for that ID", "Drop silently always", "Terminate system"], a: 1 },
        { q: "Purpose of request IDs:", opts: ["File sharing only", "Prevent duplicate operations (e.g. double charge)", "Increase multicast speed", "Make TCP unnecessary"], a: 1 },
        { q: "ACK in standard approaches:", opts: ["Database query", "Optional acknowledgments for request receipt", "UDP only", "Replaces request_id"], a: 1 },
        { q: "Connection-oriented: peers must first:", opts: ["Encrypt data", "Skip dialog", "Establish logical/physical channel", "Multicast only"], a: 2 },
        { q: "Setup/tear-down of connection trouble:", opts: ["Extremely cheap for small messages", "Relatively costly for small messages", "Messages always guaranteed", "Removes overhead"], a: 1 },
        { q: "Typical connection-oriented client:", opts: ["Sends without setup", "Setup, send request, reply on same connection, tear down", "Never tears down", "Destroys after send only"], a: 1 },
        { q: "TCP setup for small request/reply includes:", opts: ["1 packet", "2 packets", "3-way handshake: SYN, SYN-ACK, ACK", "No handshake"], a: 2 },
        { q: "In UDP (connectionless):", opts: ["Handshake and teardown", "Client one packet, server one packet reply", "Setup mandatory", "Replies never sent"], a: 1 },
        { q: "Client-server application layering:", opts: ["Transport, Network, Data link", "Presentation, Session, Transport", "User-interface, Processing, Data", "Routing, Switching, Physical"], a: 2 },
        { q: "Data level contains:", opts: ["User interaction programs", "HTML generators only", "Actual persistent data applications operate on", "Query ranking only"], a: 2 }
      ],
      tf: [
        { q: "IP (Internet Protocol) is a connection-oriented network-layer protocol.", a: false, fix: "IP is connectionless." },
        { q: "In the two-tiered architecture, a server may sometimes act as a client.", a: false, fix: "That is three-tiered architecture." },
        { q: "In horizontal distribution, different application components are placed on different machines.", a: false, fix: "That is vertical distribution." },
        { q: "In connectionless protocols, sender and receiver first explicitly establish a connection.", a: false, fix: "That is connection-oriented." },
        { q: "In a connectionless network all packets arrive in the correct sequence.", a: false, fix: "Connection-oriented networks help ordering." },
        { q: "UDP (User Datagram Protocol) is a connectionless transport protocol.", a: true },
        { q: "T/TCP (not TCP) combines connection setup with sending the request and answer with closing.", a: false, fix: "T/TCP does that, not plain TCP." },
        { q: "With synchronous communication, the sender continues immediately after submitting its message.", a: false, fix: "That describes asynchronous communication." },
        { q: "In connection-oriented networks, one packet may take a different route and arrive earlier.", a: false, fix: "That can happen in connectionless networks." },
        { q: "In vertical distribution, a client or server may be replicated.", a: false, fix: "Replication is horizontal distribution." },
        { q: "TCP is not tailored to support synchronous request-reply client-server behaviour.", a: true },
        { q: "A benefit of UDP vs TCP is that UDP works reliably over any network.", a: false, fix: "TCP provides reliability; UDP does not." },
        { q: "In connectionless protocols, client resend on no reply is always the best lost-message solution.", a: false, fix: "There is no single solution." },
        { q: "In three-tiered architecture, programs are distributed as pure clients and servers only.", a: false, fix: "That is two-tiered; three-tier allows server as client." },
        { q: "On inherently unreliable networks, connectionless protocol is always better.", a: false, fix: "Use reliable connection-oriented protocols." },
        { q: "A server process implements a specific service (e.g. file system or database).", a: true },
        { q: "A client sends a request and waits for the server reply.", a: true },
        { q: "A client process implements a specific service like a file system.", a: false, fix: "That describes a server process." },
        { q: "A server process requests service by sending a request and waiting.", a: false, fix: "That describes a client process." },
        { q: "Client-server communication can use a simple connectionless protocol.", a: true },
        { q: "Connectionless protocol can be used when the network is fairly reliable (e.g. LAN).", a: true },
        { q: "Connectionless protocol is ideal when the network is unreliable (e.g. WAN).", a: false, fix: "Often used on fairly reliable LANs." },
        { q: "Under connectionless communication, data is sent without ensuring recipient is ready.", a: true },
        { q: "IP and UDP are connectionless protocols.", a: true },
        { q: "IP and UDP are connection-oriented protocols.", a: false, fix: "They are connectionless." },
        { q: "Connectionless communication has lower overhead than connection-oriented.", a: true },
        { q: "Connection-oriented communication has lower overhead than connectionless.", a: false, fix: "Connectionless has lower overhead." },
        { q: "Connectionless communication allows multicast and broadcast easily.", a: true },
        { q: "In connectionless communication, the client cannot tell if the request or reply was lost.", a: true },
        { q: "In wide-area systems communication is inherently unreliable.", a: true },
        { q: "In wide-area systems communication is inherently reliable.", a: false, fix: "WAN communication is unreliable." },
        { q: "In connection-oriented communication, peers establish a channel before user data.", a: true },
        { q: "In connectionless communication, peers must establish a channel before user data.", a: false, fix: "Connection-oriented requires setup first." },
        { q: "TCP is a connection-oriented transport protocol.", a: true },
        { q: "TCP is a connectionless transport protocol.", a: false, fix: "TCP is connection-oriented." },
        { q: "In connection-oriented communication, client sets up connection before sending request.", a: true },
        { q: "In connectionless communication, client sets up connection before sending request.", a: false, fix: "Connection-oriented requires setup." },
        { q: "Connection setup/teardown is costly for small request-reply messages.", a: true },
        { q: "In connectionless communication, setup/teardown is costly for small messages.", a: false, fix: "That applies to connection-oriented." },
        { q: "User-interface level contains what is needed to interface directly with the user.", a: true },
        { q: "Processing level typically contains the applications.", a: true },
        { q: "Data level contains the actual data being acted on.", a: true },
        { q: "Processing level contains display management for the user.", a: false, fix: "That is the user-interface level." },
        { q: "User-interface level typically contains the applications.", a: false, fix: "Applications are in the processing level." },
        { q: "Processing level contains the actual data acted on.", a: false, fix: "Data is in the data level." },
        { q: "Processing level consists of programs that let end users interact with applications.", a: false, fix: "That is the user-interface level." },
        { q: "Data level contains the core functionality of an application.", a: false, fix: "Core functionality is in the processing level." },
        { q: "Processing level maintains the actual data the applications operate on.", a: false, fix: "That is the data level." },
        { q: "There are several ways to physically distribute a client-server application.", a: true },
        { q: "In multi-tiered architectures, application programs are distributed across clients and servers.", a: true },
        { q: "Vertical distribution places different logical components on different machines.", a: true },
        { q: "In horizontal distribution, a client/server may be split into parts on shared data subsets.", a: true }
      ]
    },
    {
      id: 5,
      title: "Chapter 5 – Communication & OSI",
      mcq: [
        { q: "Communication in DS is fundamentally based on:", opts: ["File sharing", "Low-level message passing by underlying network", "Encryption only", "Routing tables only"], a: 1 },
        { q: "Processes must agree on:", opts: ["Physical cable type", "Meaning of the bits being sent", "User passwords", "CPU speed"], a: 1 },
        { q: "Process A communicates with B by:", opts: ["Printing on paper", "Building message + system call for OS to send", "Setup only at receiver", "Bypassing OS"], a: 1 },
        { q: "Low-level agreement example:", opts: ["HTTP headers meaning", "UI design", "Volts for 0-bit and 1-bit", "Database schema"], a: 2 },
        { q: "OSI model developed by:", opts: ["IETF", "ISO", "IEEE", "DoD"], a: 1 },
        { q: "OSI model identifies:", opts: ["Only software layers", "Only routing algorithms", "Levels and which layer does which job", "Only physical medium"], a: 2 },
        { q: "Each OSI layer mainly:", opts: ["Works without other layers", "Covers activities and provides service to next higher layer", "Only encryption", "Only IP addressing"], a: 1 },
        { q: "OSI shields upper layers from:", opts: ["All lower hardware", "Application requirements", "Details of how services below are implemented", "Need for headers"], a: 2 },
        { q: "OSI protocol types by connection:", opts: ["Symmetric/asymmetric", "Encrypted/not encrypted", "Wired/wireless", "Connection-oriented and connectionless"], a: 3 },
        { q: "Connection-oriented protocol requires:", opts: ["Packets never numbered", "No agreement needed", "Connection explicitly established first", "Receiver available before setup"], a: 2 },
        { q: "Connectionless protocol requires:", opts: ["No setup in advance", "Permanent connection", "Three-way handshake always", "Synchronization checkpoints"], a: 0 },
        { q: "Connection-oriented example:", opts: ["UDP datagrams", "ATM virtual path", "Telephone system", "Dropping letter in mailbox"], a: 2 },
        { q: "Connectionless example:", opts: ["TCP handshake", "ATM setup", "Telephone call setup", "Dropping a letter in a mailbox"], a: 3 },
        { q: "OSI communication divided into:", opts: ["4 layers", "6 layers", "7 layers", "5 layers"], a: 2 },
        { q: "On receiving side, each layer:", opts: ["Only checks physical signal", "Adds more headers", "Strips and examines its own header", "Ignores trailers"], a: 2 },
        { q: "Protocol suite/stack is:", opts: ["Physical connector only", "OSI reference model only", "Collection of protocols in a system", "One protocol in isolation"], a: 2 },
        { q: "Three lowest OSI layers:", opts: ["Physical, Data Link, Network", "Transport, Session, Presentation", "Application, Presentation, Session", "Application, Transport, Network"], a: 0 },
        { q: "Physical layer concerned with:", opts: ["Routing end-to-end", "Delivering process-to-process", "Managing sessions", "Transmitting 0s and 1s"], a: 3 },
        { q: "Data Link groups bits into:", opts: ["Web pages", "Segments only", "Frames", "Spreadsheets"], a: 2 },
        { q: "Data Link error detection uses:", opts: ["Checksum/parity", "GUI rendering", "IP routing", "Certificate signing"], a: 0 },
        { q: "Sequence numbers in Data Link help:", opts: ["Convert encryption keys", "Choose route", "Identify frames", "Set HTTP sessions"], a: 2 },
        { q: "Routing is primary task of:", opts: ["Physical layer", "Data Link layer", "Network layer", "Application layer"], a: 2 },
        { q: "Network layer delivers:", opts: ["Individual packets source to destination host", "Encrypted pages to browser", "Frames app to app", "User-interface display"], a: 0 },
        { q: "X.25 vs IP:", opts: ["X.25 connection-oriented, IP connectionless", "Both connectionless", "Both connection-oriented", "X.25 connectionless, IP connection-oriented"], a: 0 },
        { q: "In X.25, user first sends:", opts: ["FIN request", "SYN after data", "Call Request to destination", "Multicast request"], a: 2 },
        { q: "In X.25 after acceptance caller gets:", opts: ["MAC address", "Checksum", "HTML page ID", "Connection identifier"], a: 3 },
        { q: "Connectionless IP packets:", opts: ["Only after receiver ready", "Only with three-way handshake", "Without any setup", "Only after setup established"], a: 2 },
        { q: "Transport layer provides (if packets lost):", opts: ["Reliable connection", "Encryption for presentation", "Header formatting", "Modem signaling"], a: 0 },
        { q: "TCP is used as:", opts: ["Connectionless transport", "Physical standard only", "Data Link protocol", "DoD/Internet transport protocol"], a: 3 },
        { q: "Layer detecting/correcting communication errors:", opts: ["Physical", "Data Link", "Presentation", "Transport"], a: 1 },
        { q: "Layer grouping bits into frames:", opts: ["Physical", "Data Link", "Presentation", "Transport"], a: 1 },
        { q: "Delivery of packets source to destination host:", opts: ["Transport", "Data Link", "Network", "All of the previous"], a: 2 },
        { q: "Which packets sent/received tracked by:", opts: ["Physical", "Data Link", "Presentation", "Transport"], a: 3 },
        { q: "Which packets retransmitted:", opts: ["Transport", "Data Link", "Network", "None"], a: 0 },
        { q: "Organize/manage connections per application:", opts: ["Session", "Presentation", "Data Link", "None"], a: 0 },
        { q: "Dialog control and synchronization:", opts: ["Session", "Presentation", "Network", "Data Link"], a: 0 },
        { q: "Translation, compression, encryption:", opts: ["Session", "Presentation", "Data Link", "Network"], a: 1 },
        { q: "Reliable connection protocol layer:", opts: ["Physical", "Transport", "Network", "None"], a: 1 },
        { q: "Lowest OSI layers:", opts: ["Physical", "Data Link", "Network", "All of the previous"], a: 3 },
        { q: "Protect resource against simultaneous distributed access:", opts: ["Authentication", "Distributed commit", "Distributed locking", "None"], a: 2 },
        { q: "Transport protocol for real-time data:", opts: ["UDP", "TCP", "RTP", "None"], a: 2 },
        { q: "Layer that transmits message machine 1→2:", opts: ["Transport", "Network", "Physical", "None"], a: 2 },
        { q: "Collection of protocols in a system:", opts: ["Reference model", "Protocol suite", "Protocol stack", "2 and 3"], a: 3 },
        { q: "Routing primary task:", opts: ["Transport", "Network", "Physical", "1 and 2"], a: 1 },
        { q: "Computing checksum task:", opts: ["Session", "Presentation", "Network", "Data Link"], a: 3 },
        { q: "Connectionless transport protocol:", opts: ["X.25", "IP", "TCP", "UDP"], a: 3 },
        { q: "Synchronization checkpoints in long transfers:", opts: ["Presentation", "Network", "Session", "Presentation (dup)"], a: 2 },
        { q: "Predefined virtual path protocol:", opts: ["X.25", "IP", "ATM", "HTTP"], a: 2 },
        { q: "Packets sent without setup, no path remembered:", opts: ["X.25", "IP", "ATM", "All"], a: 1 },
        { q: "Lost packet retransmission task:", opts: ["Transport", "Network", "Data Link", "1 and 2"], a: 0 },
        { q: "Protocol for managing Web page transfer:", opts: ["TCP", "HTTP", "UDP", "None"], a: 1 },
        { q: "Atomicity of operations:", opts: ["Authentication", "Distributed commit protocols", "Distributed locking", "None"], a: 1 },
        { q: "Electrical/mechanical/signaling interfaces:", opts: ["Physical", "Data Link", "Network", "None"], a: 0 },
        { q: "HTTP belongs to:", opts: ["Application", "Transport", "Network", "None"], a: 0 },
        { q: "Cross-platform translation to local format:", opts: ["Presentation", "Session", "Network", "Presentation (dup)"], a: 0 }
      ],
      tf: [
        { q: "Communication in distributed systems is based on low-level message passing from the network.", a: true },
        { q: "Before sending bits, processes do not need to agree on the meaning of those bits.", a: false, fix: "They must agree to prevent confusion." },
        { q: "Process A builds a message in its own address space before communicating with B.", a: true },
        { q: "After building the message, A does not use a system call to send it over the network.", a: false, fix: "A uses a system call so the OS sends it to B." },
        { q: "Layered protocols reduce confusion by defining agreements at multiple levels.", a: true },
        { q: "Sender and receiver agree only at the application level, not lower levels.", a: false, fix: "Agreements are needed at many levels." },
        { q: "ISO developed the OSI reference model for communication.", a: true },
        { q: "The OSI model has 5 layers.", a: false, fix: "The OSI model has 7 layers." },
        { q: "Each OSI layer covers different network activities, equipment, and protocols.", a: true },
        { q: "Each OSI layer provides service to the next-higher layer and prepares data for delivery.", a: true },
        { q: "The OSI reference model defines which layer should do which job.", a: true },
        { q: "Connection-oriented communication does not require connection establishment.", a: false, fix: "Sender and receiver must establish a connection first." },
        { q: "The telephone is an example of connection-oriented communication.", a: true },
        { q: "Connectionless communication requires a pre-established connection.", a: false, fix: "No setup in advance is needed." },
        { q: "Dropping a letter in a mailbox is connectionless communication.", a: true },
        { q: "In OSI, higher layers remove headers and lower layers add them.", a: false, fix: "Lower layers add headers; receiver strips its own header." },
        { q: "When a message arrives, each layer strips and examines its own header.", a: true },
        { q: "Information in layer n header is used by layer n protocol.", a: true },
        { q: "OSI protocols were widely popular and mostly used.", a: false, fix: "Internet protocols (TCP/IP) are mostly used." },
        { q: "A protocol suite/stack is the collection of protocols used in a system.", a: true },
        { q: "The three lowest OSI layers are Physical, Data Link, and Network.", a: true },
        { q: "The physical layer moves individual bits from one hop to the next.", a: true },
        { q: "The physical layer detects and corrects communication errors.", a: false, fix: "The Data Link layer does." },
        { q: "The Data Link layer groups bits into units called frames.", a: true },
        { q: "If Data Link checksum disagrees, the receiver accepts the frame anyway.", a: false, fix: "The receiver asks the sender to retransmit." },
        { q: "Data Link assigns sequence numbers so frames can be identified.", a: true },
        { q: "Routing is the primary task of the Data Link layer.", a: false, fix: "Routing is the Network layer's primary task." },
        { q: "The shortest route is not always the best route.", a: true },
        { q: "X.25 is connectionless and IP is connection-oriented.", a: false, fix: "X.25 is connection-oriented; IP is connectionless." },
        { q: "The transport layer provides a reliable connection even if packets can be lost.", a: true },
        { q: "The network layer detects and corrects communication errors.", a: false, fix: "The Data Link layer does." },
        { q: "X.25 is a connectionless network-layer protocol.", a: false, fix: "X.25 is connection-oriented." },
        { q: "IP is a connection-oriented network-layer protocol.", a: false, fix: "IP is connectionless." },
        { q: "In ATM, a virtual path is a predefined route between two hosts.", a: true },
        { q: "Each IP packet is routed independently; no path is remembered.", a: true },
        { q: "In connection-oriented networks, packets may arrive out of order on different routes.", a: false, fix: "That can happen in connectionless networks." },
        { q: "Fault-tolerance lets a system continue operating despite component failures.", a: true },
        { q: "UDP works reliably over any network compared to TCP.", a: false, fix: "TCP provides reliability; UDP does not." },
        { q: "TCP is not tailored for synchronous request-reply client-server interaction.", a: true },
        { q: "TCP (not T/TCP) combines setup with request and answer with closing.", a: false, fix: "T/TCP does that." },
        { q: "The middleware layer contains application-independent protocols.", a: true },
        { q: "The Session layer is concerned with the meaning of the bits.", a: false, fix: "The Presentation layer handles data meaning/format." },
        { q: "In the Internet protocol suite, the Session layer provides synchronization.", a: false, fix: "The Session layer is not present in the Internet suite." },
        { q: "Distributed commit protocols protect resources against simultaneous distributed access.", a: false, fix: "Distributed locking protocols do." },
        { q: "Authentication protocols grant access only to authorized resources.", a: false, fix: "Authorization protocols do; authentication verifies identity." },
        { q: "The Data Link layer defines connector size, pins, and electrical interfaces.", a: false, fix: "The Physical layer does." },
        { q: "Routing is the primary task of the physical layer.", a: false, fix: "Routing is the Network layer's task." },
        { q: "In an m-layer model, layer n header is used for layer (m−n) protocol.", a: false, fix: "Layer n header is used by layer n protocol." },
        { q: "The physical layer moves individual bits from one node to the next.", a: true },
        { q: "The data link layer moves individual bits from one node to the next.", a: false, fix: "The physical layer does." },
        { q: "The data link layer detects and corrects communication errors.", a: true },
        { q: "The physical layer detects and corrects communication errors.", a: false, fix: "The Data Link layer does." },
        { q: "The data link layer delivers packets from source host to destination host.", a: false, fix: "The Network layer does." },
        { q: "ATM is an asynchronous connection-oriented protocol.", a: true },
        { q: "The session layer handles dialog control and synchronization.", a: true },
        { q: "The presentation layer handles dialog control and synchronization.", a: false, fix: "The session layer does." },
        { q: "Internet Explorer performs session, presentation, and application layer functions.", a: true },
        { q: "The presentation layer handles translation, compression, and encryption.", a: true },
        { q: "The session layer handles translation, compression, and encryption.", a: false, fix: "The presentation layer does." }
      ]
    }
  ]
};
